FROM ubuntu

RUN apt update
RUN sudo apt-get install texlive-latex-recommended texlive-latex-extra \
                    texlive-fonts-recommended texlive-fonts-extra \
                    texlive-xetex latexmk